//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionDeStock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetGestionDeStock.MainUser", typeof(MainUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_BlindCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.BlindCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_MosaicCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.MosaicCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_MosaicShift {
            get {
                object obj = ResourceManager.GetObject("animation1.MosaicShift", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=1, Y=1}.
        /// </summary>
        internal static System.Drawing.PointF animation1_ScaleCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.ScaleCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=1, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_SlideCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.SlideCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation2_BlindCoeff {
            get {
                object obj = ResourceManager.GetObject("animation2.BlindCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=200, Y=200}.
        /// </summary>
        internal static System.Drawing.PointF animation2_MosaicCoeff {
            get {
                object obj = ResourceManager.GetObject("animation2.MosaicCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0.5}.
        /// </summary>
        internal static System.Drawing.PointF animation2_MosaicShift {
            get {
                object obj = ResourceManager.GetObject("animation2.MosaicShift", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation2_ScaleCoeff {
            get {
                object obj = ResourceManager.GetObject("animation2.ScaleCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation2_SlideCoeff {
            get {
                object obj = ResourceManager.GetObject("animation2.SlideCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation3_BlindCoeff {
            get {
                object obj = ResourceManager.GetObject("animation3.BlindCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation3_MosaicCoeff {
            get {
                object obj = ResourceManager.GetObject("animation3.MosaicCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation3_MosaicShift {
            get {
                object obj = ResourceManager.GetObject("animation3.MosaicShift", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation3_ScaleCoeff {
            get {
                object obj = ResourceManager.GetObject("animation3.ScaleCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=1, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation3_SlideCoeff {
            get {
                object obj = ResourceManager.GetObject("animation3.SlideCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=541,Y=17}.
        /// </summary>
        internal static System.Drawing.Point bunifuDragControl1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bunifuDragControl1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point bunifuElipse1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bunifuElipse1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=141,Y=17}.
        /// </summary>
        internal static System.Drawing.Point LogoAnimator_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("LogoAnimator.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=271,Y=17}.
        /// </summary>
        internal static System.Drawing.Point PanelAnimator_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("PanelAnimator.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=403,Y=17}.
        /// </summary>
        internal static System.Drawing.Point PanelAnimator2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("PanelAnimator2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PB_logo_Image {
            get {
                object obj = ResourceManager.GetObject("PB_logo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Slider_Image {
            get {
                object obj = ResourceManager.GetObject("Slider.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
